workflows:

  build-app:

    name: Build Android and iOS

    instance_type: mac_mini_m1

    environment:

      vars:

        NODE_VERSION: latest

        EXPO_CLI_VERSION: latest

      flutter: stable  # Include this if you're using Flutter as well; otherwise, it's optional

    scripts:

      # Install dependencies and the new local Expo CLI

      - name: Install dependencies

        script: |

          npm install -g eas-cli

          npm install




      # Build Android APK

      - name: Build Android

        script: |

          eas build -p android




      # Build iOS IPA

      - name: Build iOS

        script: |

          eas build -p ios




    artifacts:

      - android/app/build/outputs/**/*.apk

      - ios/build/*.ipa  # Adjust based on your expo build output