workflows:
  build-app:
    name: Build Android and iOS
    instance_type: mac_mini_m2  # Change this to mac_mini_m1 if needed
    environment:
      vars:
        NODE_VERSION: latest
        EXPO_CLI_VERSION: latest
      flutter: stable  # Include this if you're using Flutter as well; otherwise, it's optional
    scripts:
      # Install dependencies
      - name: Install dependencies
        script: |
          npm install -g expo-cli@$EXPO_CLI_VERSION
          npm install

      # Build Android APK
      - name: Build Android
        script: |
          expo build:android --no-publish 

      # Build iOS IPA
      - name: Build iOS
        script: |
          expo build:ios --no-publish 

    artifacts:
      - android/app/build/outputs/**/*.apk
      - ios/build/*.ipa  # Adjust based on your expo build output
